name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allow manual triggering from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Generate the snake GIF and SVG
      - uses: Platane/snk@v1.6.0  # Use a stable release
        id: snake-gif
        with:
          github_user_name: sofialtamsh
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the git repo for debugging
      - run: git status

      # Push the generated files to the 'output' branch
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0  # Use stable version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # Push to 'output' branch, not 'master'
          force: true

      # Deploy the files to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
